name: tests-payments

on:
  pull_request: # any time PR created, updated or re-opened
    paths:
      - "payments/**" # only if changes in payments dir

jobs:
  build: # starts a vm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # takes all code of the project
      - run: cd payments && npm install && npm run && npm run test:ci # runs test scripts inside payments service

