name: tests-tickets

on:
  pull_request: # any time PR created, updated or re-opened
    paths:
      - "tickets/**" # only if changes in tickets dir

jobs:
  build: # starts a vm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # takes all code of the project
      - run: cd tickets && npm install && npm run && npm run test:ci # runs test scripts inside tickets service

