name: tests-orders

on:
  pull_request: # any time PR created, updated or re-opened

jobs:
  build: # starts a vm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # takes all code of the project
      - run: cd orders && npm install && npm run && npm run test:ci # runs test scripts inside orders service

